-- V1__create_bookings_table.sql
CREATE TABLE bookings (
    id BIGSERIAL PRIMARY KEY,
    mobile VARCHAR(20) NOT NULL,
    added_time TIMESTAMP,
    modified_time TIMESTAMP,
    task_id BIGINT,
    name VARCHAR(255),
    status INT,
    address TEXT,
    google_address TEXT,
    google_address_id BIGINT,
    booking_payment INT,
    installation_payment INT,
    plan_id INT,
    setting_id INT,
    ssid VARCHAR(255),
    wifi_pass VARCHAR(255),
    b_fee_category VARCHAR(255),
    subscription BOOLEAN,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    payment_status INT DEFAULT 0,
    lead_type VARCHAR(255),
    otp VARCHAR(50),
    pref_inst_date TIMESTAMP,
    has_paid_online BOOLEAN,
    wiom_member BOOLEAN,
    booking_fee_refunded_date TIMESTAMP,
    cancellation_booking_date TIMESTAMP,
    cancel_reason TEXT,
    account_id BIGINT,
    nasid BIGINT,
    lco_account_id BIGINT,
    device_id VARCHAR(255),
    integration_point VARCHAR(255),
    installation_payment_txn_id VARCHAR(255),
    installation_reward INT DEFAULT 0,
    booking_reward INT DEFAULT 0,
    autopay_reward INT,
    booking_payment_txn_id VARCHAR(255),
    event_map TEXT,
    is_coupon_applied BOOLEAN,
    mandate_info TEXT,
    booking_refund_amount INT,
    rebooking_payment INT,
    rebooking_payment_txn_id VARCHAR(255),
    booking_service_charge INT,
    booking_fee INT,
    is_ins_date_changed BOOLEAN,
    show_date_change BOOLEAN,
    is_available_in_city BOOLEAN,
    offering VARCHAR(255),
    shared_coupon_id BIGINT,
    lead_squared_id VARCHAR(255),
    lead_squared_state VARCHAR(255),
    shared_coupon_discount INT,
    booked_service_charge INT,
    added_epoch BIGINT,
    slot_details TEXT
);

-- Table for @ElementCollection (autopayDiscountList)
CREATE TABLE booking_autopay_discount_list (
    booking_id BIGINT NOT NULL,
    autopay_discount_list INT,
    CONSTRAINT fk_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE
);
